- name: Publish a Python distribution to PyPI
  on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]
  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: pypa/gh-action-pypi-publish@release/v1
          with:
            user: __token__
            password: ${{ secrets.PYPI_API_TOKEN }}
